# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('infrastructure', '0002_auto_20180104_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='infrastructure.Platform'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='locations.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='serialport',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='powerport',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='poweroutlet',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('device', 'name')]),
        ),
    ]
