# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20180104_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicebaytemplate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='devicebaytemplate',
            name='device_definition',
        ),
        migrations.DeleteModel(
            name='DeviceBayTemplate',
        ),
    ]
