# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20180104_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedefinition',
            name='subdevice_role',
        ),
    ]
