# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_remove_devicedefinition_subdevice_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweroutlet',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='powerport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='serialport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='infrastructure.DeviceDefinition'),
        ),
    ]
