# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
        ('infrastructure', '0006_auto_20180104_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.MACAddress'),
        ),
    ]
