# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('ipam', '0004_auto_20180119_1659'),
        ('infrastructure', '0007_interface_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('discovered', models.BooleanField(default=False, verbose_name='Discovered')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='inventory.Asset')),
            ],
            options={
                'ordering': ['device__id', 'parent__id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_ip4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ip4_for', to='ipam.IPAddress', verbose_name='Primary IPv4'),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_ip6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ip6_for', to='ipam.IPAddress', verbose_name='Primary IPv6'),
        ),
        migrations.AddField(
            model_name='component',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='infrastructure.Device'),
        ),
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='infrastructure.Component'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set([('device', 'parent', 'name')]),
        ),
    ]
