# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contacts', '0010_hardwaresupplier'),
        ('places', '0002_country_locality_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('asset_tag', models.SlugField(editable=False, max_length=8, verbose_name='Asset tag')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('serial_number', models.CharField(blank=True, max_length=48, null=True, verbose_name='Serial number')),
                ('active', models.BooleanField(default=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='items', to='contacts.Organization', verbose_name='Assigned to')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('assets', models.ManyToManyField(blank=True, to='inventory.Asset', verbose_name='Assets')),
            ],
            options={
                'verbose_name': 'Asset group',
                'verbose_name_plural': 'Asset groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset state',
                'verbose_name_plural': 'Asset state',
            },
        ),
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('model', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('part_number', models.CharField(blank=True, help_text='Discrete part number (optional)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_templates', to='contacts.Manufacturer')),
                ('suppliers', models.ManyToManyField(blank=True, to='contacts.HardwareSupplier', verbose_name='Suppliers')),
                ('supplies', models.ManyToManyField(blank=True, related_name='_baseitem_supplies_+', to='inventory.BaseItem', verbose_name='Supplies')),
            ],
            options={
                'verbose_name': 'Base item',
                'verbose_name_plural': 'Base items',
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & time')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCPQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryCheckPoint', verbose_name='Check point')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BaseItem', verbose_name='Supply')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Stockroom transaction',
                'verbose_name_plural': 'Stockroom transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Date & time')),
                ('action', models.CharField(max_length=32, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='User defined ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Date required')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agreed price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('received_qty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='received')),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BaseItem', verbose_name='Asset template')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.PurchaseOrder', verbose_name='Purchase order')),
            ],
            options={
                'verbose_name': 'Purchase order item',
                'verbose_name_plural': 'Purchase order items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase order item status',
                'verbose_name_plural': 'Purchase order item status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase order status',
                'verbose_name_plural': 'Purchase order status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='User defined ID (optional)')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Date required')),
                ('budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('originator', models.CharField(blank=True, max_length=64, null=True, verbose_name='Originator')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BaseItem', verbose_name='Asset template')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.PurchaseRequest', verbose_name='Purchase request')),
            ],
            options={
                'verbose_name': 'Purchase request item',
                'verbose_name_plural': 'Purchase request items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purchase request status',
                'verbose_name_plural': 'Purchase request status',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
            ],
            options={
                'verbose_name': 'Asset state',
                'verbose_name_plural': 'Asset states',
            },
        ),
        migrations.CreateModel(
            name='Stockroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Stockroom',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseRequestStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseOrderItemStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseRequest', verbose_name='Purchase request'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseOrderStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='contacts.HardwareSupplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='stockroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.Stockroom', verbose_name='Stockroom'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BaseItem', verbose_name='Supply'),
        ),
        migrations.AddField(
            model_name='inventorycheckpoint',
            name='stockroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stockroom', verbose_name='Stockroom'),
        ),
        migrations.AddField(
            model_name='inventorycheckpoint',
            name='supplies',
            field=models.ManyToManyField(blank=True, through='inventory.InventoryCPQty', to='inventory.BaseItem', verbose_name='Supplies'),
        ),
        migrations.AddField(
            model_name='assetstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='asset',
            name='base_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.BaseItem', verbose_name='Asset template'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='General location'),
        ),
        migrations.AlterUniqueTogether(
            name='baseitem',
            unique_together=set([('manufacturer', 'model')]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('base_item', 'serial_number')]),
        ),
    ]
