# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inventory.item',),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='purchaserequestitem',
            old_name='base_item',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='requires',
        ),
        migrations.AddField(
            model_name='item',
            name='built_to_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RELEASED', 'Released'), ('RECEIVED', 'Received'), ('CHANGED', 'Changed'), ('CANCELED', 'Canceled'), ('CLOSED', 'Closed')], default='NEW', max_length=10, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RELEASED', 'Released'), ('RECEIVED', 'Received')], default='NEW', max_length=10, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStatus',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestStatus',
        ),
        migrations.AddField(
            model_name='itemparts',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='itemparts',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='item',
            name='parts',
            field=models.ManyToManyField(blank=True, through='inventory.ItemParts', to='inventory.Part', verbose_name='Requires'),
        ),
    ]
