# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='Description'),
        ),
    ]
