# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20171117_1659'),
        ('inventory', '0003_auto_20171114_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='originator',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Item'),
        ),
    ]
