# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20171117_1659'),
        ('inventory', '0004_auto_20171117_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='supplier_contact',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier_emailaddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.EmailAddress'),
            preserve_default=False,
        ),
    ]
