# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20171117_1659'),
        ('inventory', '0005_auto_20171117_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='supplier_emailaddress',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier_email_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.EmailAddress', verbose_name='Supplier Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='User defined ID (optional)'),
            preserve_default=False,
        ),
    ]
