# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20171117_1919'),
        ('inventory', '0006_auto_20171117_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='supplier_email_address',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_pr_set', to='inventory.PurchaseRequest'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.EmailAddress'),
        ),
    ]
