# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20171117_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.SlugField(editable=False, max_length=8, unique=True, verbose_name='Asset tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, default='00000000', max_length=100, verbose_name='Serial number'),
            preserve_default=False,
        ),
    ]
