# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
    ]
