# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.PositiveSmallIntegerField(default=1000)),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subnet',
            name='role',
            field=models.ManyToManyField(blank=True, to='ipam.Role'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='role',
            field=models.ManyToManyField(blank=True, to='ipam.Role'),
        ),
    ]
