# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_interface_mac_address'),
        ('ipam', '0002_auto_20180110_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['version', 'address'], 'verbose_name': 'IP address', 'verbose_name_plural': 'IP addresses'},
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Interface'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='nat_inside',
            field=models.OneToOneField(blank=True, help_text='The IP for which this address is the "outside" IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_outside', to='ipam.IPAddress', verbose_name='NAT (Inside)'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Loopback'), (20, 'Secondary'), (30, 'Anycast'), (40, 'VIP'), (41, 'VRRP'), (42, 'HSRP'), (43, 'GLBP'), (44, 'CARP')], help_text='The functional role of this IP', null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Reserved'), (3, 'Deprecated'), (5, 'DHCP')], default=1, help_text='The operational status of this IP', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.VRF'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ipam.Subnet'),
        ),
    ]
