# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_auto_20180116_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipam.Space'),
        ),
    ]
