# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 22:18
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_auto_20180119_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRangeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('managed', models.BooleanField(default=True, help_text='When true, no automated system will ever assign IP addresses inside this range. They can be used for anything (e.g. infrastructure systems, network hardware, external DHCP, etc.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='iprange',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.IPRangeRole'),
        ),
    ]
