# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20170907_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
