# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0003_auto_20171120_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('site_tag', models.SlugField(editable=False, max_length=8, unique=True, verbose_name='Site tag')),
                ('facility', models.CharField(blank=True, help_text='Used to include an external designation such as a data center name (e.g. Equinix TR1)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('places', models.ManyToManyField(to='places.Place')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
