# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('information_type', models.CharField(choices=[('assistant', 'Assistant'), ('business', 'Business'), ('business-other', 'Business, other'), ('company', 'Company'), ('home', 'Home'), ('home-other', 'Home, other'), ('other', 'Other'), ('primary', 'Primary')], default='primary', max_length=20)),
                ('primary', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'email address',
                'verbose_name_plural': 'email addresses',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='contacts.Organization')),
            ],
            options={
                'verbose_name': 'organization alias',
                'verbose_name_plural': 'organization aliases',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='PeopleOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=150)),
                ('role_en', models.CharField(blank=True, max_length=150, null=True)),
                ('role_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='people', to='contacts.ContactGroup', verbose_name='groups')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_roles', to='contacts.Organization')),
            ],
            options={
                'verbose_name': 'Person Organization',
                'verbose_name_plural': 'People Organizations',
                'ordering': ('organization__name', 'person__full_name'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('slug', models.SlugField(editable=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('suffix_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('suffix_fr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('full_name', models.CharField(editable=False, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('O', 'Other')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('custom_avatar_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organizations', models.ManyToManyField(blank=True, through='contacts.PeopleOrganizations', to='contacts.Organization')),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ('last_name', 'first_name'),
                'permissions': (('view_person', 'Can view person'),),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('country_code', models.CharField(default='1', max_length=10, verbose_name='country code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='number')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='extension')),
                ('information_type', models.CharField(choices=[('assistant', 'Assistant'), ('business', 'Business'), ('business-fax', 'Business fax'), ('business-other', 'Business, other'), ('callback', 'Callback'), ('car', 'Car'), ('company', 'Company'), ('home', 'Home'), ('home-fax', 'Home fax'), ('home-other', 'Home, other'), ('isdn', 'ISDN'), ('mobile', 'Mobile'), ('other', 'Other'), ('other-fax', 'Other fax'), ('pager', 'Pager'), ('primary', 'Primary'), ('radio', 'Radio'), ('tty-tdd', 'TTY/TDD')], default='primary', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contacts.Organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contacts.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('information_type', models.CharField(choices=[('assistant', 'Assistant'), ('business', 'Business'), ('business-other', 'Business, other'), ('company', 'Company'), ('home', 'Home'), ('home-other', 'Home, other'), ('other', 'Other'), ('primary', 'Primary')], max_length=12)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='contacts.Organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='contacts.Person', verbose_name='person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='places.Place')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('url', models.URLField(verbose_name='URL')),
                ('information_type', models.CharField(choices=[('Social media', (('apple', 'Apple'), ('behance', 'Behance'), ('bitbucket', 'BitBucket'), ('delicious', 'Delicious'), ('deviantart', 'DeviantArt'), ('facebook', 'Facebook'), ('flickr', 'Flickr'), ('github', 'Github'), ('googleplus', 'Google+'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tumblr', 'Tumblr'), ('twitter', 'Twitter'), ('youtube', 'YouTube'))), ('Web site', (('assistant', 'Assistant'), ('business', 'Business'), ('business-other', 'Business, other'), ('company', 'Company'), ('home', 'Home'), ('home-other', 'Home, other'), ('other', 'Other'), ('primary', 'Primary')))], max_length=12)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='contacts.Organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='contacts.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.AddField(
            model_name='peopleorganizations',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_departments', to='contacts.Person', verbose_name='managers'),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='contacts.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='departments', to='contacts.Person', verbose_name='people'),
        ),
        migrations.AddField(
            model_name='organization',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='managed_organizations', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='organization',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='contacts.ContactGroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contacts.Organization', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='organization',
            name='people',
            field=models.ManyToManyField(blank=True, through='contacts.PeopleOrganizations', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='contacts.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='contacts.Person', verbose_name='person'),
        ),
        migrations.CreateModel(
            name='HardwareSupplier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('contacts.organization',),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('contacts.organization',),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set([('country_code', 'phone_number', 'extension', 'person'), ('country_code', 'phone_number', 'extension', 'organization')]),
        ),
    ]
