# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleorganizations',
            name='groups',
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='people', to='contacts.ContactGroup', verbose_name='groups'),
        ),
    ]
