# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170829_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='jonathan-senecal', editable=False),
            preserve_default=False,
        ),
    ]
