# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
