# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170829_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationalias',
            options={'ordering': ('name',), 'verbose_name': 'organization alias', 'verbose_name_plural': 'organization aliases'},
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='zap', editable=False),
            preserve_default=False,
        ),
    ]
