# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('contacts', '0007_person_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('information_type', models.CharField(choices=[('assistant', 'Assistant'), ('business', 'Business'), ('business-other', 'Business, other'), ('company', 'Company'), ('home', 'Home'), ('home-other', 'Home, other'), ('other', 'Other'), ('primary', 'Primary')], max_length=12)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='contacts.Organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='contacts.Person', verbose_name='person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='places.Place')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
