# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('contacts.organization',),
        ),
    ]
