# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_hardwaresupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Person Organization',
                'verbose_name_plural': 'People Organizations',
                'ordering': ('organization__name', 'person__name'),
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='people',
        ),
        migrations.AlterField(
            model_name='organization',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='managed_organizations', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='personorganizations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Organization'),
        ),
        migrations.AddField(
            model_name='personorganizations',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='people', through='contacts.PersonOrganizations', to='contacts.Person'),
        ),
    ]
