# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20171024_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonOrganizations',
            new_name='PeopleOrganizations',
        ),
    ]
