# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20171024_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleorganizations',
            options={'ordering': ('organization__name', 'person__full_name'), 'verbose_name': 'Person Organization', 'verbose_name_plural': 'People Organizations'},
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='FixMe', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
