# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20171024_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleorganizations',
            name='role_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='peopleorganizations',
            name='role_fr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
