# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20171024_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='suffix_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='person',
            name='suffix_fr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='person',
            name='title_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='person',
            name='title_fr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Title'),
        ),
    ]
