# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20171024_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='people',
            field=models.ManyToManyField(blank=True, through='contacts.PeopleOrganizations', to='contacts.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='contacts.PeopleOrganizations', to='contacts.Organization'),
        ),
    ]
