# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20171031_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleorganizations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_roles', to='contacts.Organization'),
        ),
        migrations.AlterField(
            model_name='peopleorganizations',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='contacts.Person'),
        ),
    ]
