# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20171114_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='people',
        ),
        migrations.AddField(
            model_name='organization',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='contacts.Organization', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='peopleorganizations',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='people', to='contacts.Person', verbose_name='groups'),
        ),
    ]
