# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20171117_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('O', 'Other')], max_length=5),
        ),
    ]
