# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest')], editable=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AddressComponentThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('address_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.AddressComponent')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(blank=True, max_length=200, null=True)),
                ('formatted_address', models.CharField(editable=False, max_length=200)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('google_place_id', models.CharField(blank=True, max_length=200, unique=True)),
                ('place_type', models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest'), ('floor', 'floor'), ('establishment', 'establishment'), ('parking', 'parking'), ('post_box', 'post_box'), ('postal_town', 'postal_town'), ('room', 'room'), ('street_number', 'street_number'), ('bus_station', 'bus_station'), ('train_station', 'train_station'), ('transit_station', 'transit_station')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('address_components', models.ManyToManyField(through='places.AddressComponentThrough', to='places.AddressComponent')),
            ],
        ),
        migrations.AddField(
            model_name='addresscomponentthrough',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AlterUniqueTogether(
            name='addresscomponent',
            unique_together=set([('long_name', 'short_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='addresscomponentthrough',
            unique_together=set([('place', 'order')]),
        ),
    ]
