# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(editable=False, max_length=200)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('google_place_id', models.CharField(max_length=200, unique=True)),
                ('place_type', models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest'), ('floor', 'floor'), ('establishment', 'establishment'), ('parking', 'parking'), ('post_box', 'post_box'), ('postal_town', 'postal_town'), ('room', 'room'), ('street_number', 'street_number'), ('bus_station', 'bus_station'), ('train_station', 'train_station'), ('transit_station', 'transit_station')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('related_places', models.ManyToManyField(related_name='_place_related_places_+', to='places.Place')),
            ],
        ),
    ]
