# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('places.addresscomponent',),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('places.addresscomponent',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('places.addresscomponent',),
        ),
    ]
