# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_country_locality_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat_long',
            new_name='point',
        ),
    ]
