# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 18:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_country_locality_sublocality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest'), ('floor', 'floor'), ('establishment', 'establishment'), ('parking', 'parking'), ('post_box', 'post_box'), ('postal_town', 'postal_town'), ('room', 'room'), ('street_number', 'street_number'), ('bus_station', 'bus_station'), ('train_station', 'train_station'), ('transit_station', 'transit_station')], max_length=30), blank=True, null=True, size=None),
        ),
    ]
