# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20171130_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='related_places',
            field=models.ManyToManyField(editable=False, related_name='_place_related_places_+', to='places.Place'),
        ),
    ]
