# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 18:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sites', '0001_initial'), ('sites', '0002_auto_20170906_1844')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(editable=False, max_length=200)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('google_place_id', models.CharField(editable=False, max_length=200)),
                ('notes', models.TextField()),
                ('raw_address', models.CharField(editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel1',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
                ('iso_code', models.CharField(default='CA', max_length=10)),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel2',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel3',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
                ('iso_code', models.CharField(max_length=10)),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='SubLocality',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='SubPremise',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.CreateModel(
            name='AddressComponentThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('addresscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.AddressComponent')),
            ],
            bases=('sites.addresscomponent',),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='component_type',
            field=models.CharField(choices=[('street_number', 'street_number'), ('route', 'route'), ('locality', 'locality'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_1', 'administrative_area_level_1'), ('sublocality', 'sublocality'), ('subpremise', 'subpremise'), ('neighborhood', 'neighborhood'), ('postal_code', 'postal_code'), ('postal_code_prefix', 'postal_code_prefix')], default='none', editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresscomponentthrough',
            name='address_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.AddressComponent'),
        ),
        migrations.AddField(
            model_name='addresscomponentthrough',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_components',
            field=models.ManyToManyField(through='sites.AddressComponentThrough', to='sites.AddressComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='addresscomponentthrough',
            unique_together=set([('place', 'order')]),
        ),
    ]
