# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_squashed_0002_auto_20170906_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativearealevel1',
            name='iso_code',
            field=models.CharField(max_length=10),
        ),
    ]
