# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 15:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20170906_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativearealevel1',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='administrativearealevel2',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='administrativearealevel3',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='route',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='sublocality',
            name='addresscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='subpremise',
            name='addresscomponent_ptr',
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest'), ('floor', 'floor'), ('establishment', 'establishment'), ('parking', 'parking'), ('post_box', 'post_box'), ('postal_town', 'postal_town'), ('room', 'room'), ('street_number', 'street_number'), ('bus_station', 'bus_station'), ('train_station', 'train_station'), ('transit_station', 'transit_station')], default='bleh', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresscomponent',
            name='component_type',
            field=models.CharField(choices=[('street_address', 'street_address'), ('route', 'route'), ('intersection', 'intersection'), ('political', 'political'), ('country', 'country'), ('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('administrative_area_level_3', 'administrative_area_level_3'), ('administrative_area_level_4', 'administrative_area_level_4'), ('administrative_area_level_5', 'administrative_area_level_5'), ('colloquial_area', 'colloquial_area'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('neighborhood', 'neighborhood'), ('premise', 'premise'), ('subpremise', 'subpremise'), ('postal_code', 'postal_code'), ('natural_feature', 'natural_feature'), ('airport', 'airport'), ('park', 'park'), ('point_of_interest', 'point_of_interest')], editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(editable=False, srid=4326),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='raw_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AdministrativeAreaLevel1',
        ),
        migrations.DeleteModel(
            name='AdministrativeAreaLevel2',
        ),
        migrations.DeleteModel(
            name='AdministrativeAreaLevel3',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Premise',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='SubLocality',
        ),
        migrations.DeleteModel(
            name='SubPremise',
        ),
    ]
